info:
  app:
    name: "@project.name@"
    version: "@project.version@"

spring:
  application.name: "@project.name@"
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa.hibernate.ddl-auto: validate
  profiles:
    active: development
  thymeleaf:
    cache: false